//
//  UIFont+IOSAdditions.swift
//
//  Generated by Zeplin on 10/19/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
	class func iosTextStyleFont() -> UIFont? {
		return UIFont(name: "PingFangSC-Medium", size: 16.0)
	}
}
